server:
  servlet:
    context-path: /easyui

mybatis:
  type-aliases-package: com.cssl.pojo
  mapper-locations: classpath:com/cssl/dao/*.xml
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///easyui
    username: root
    password: root

  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8